# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: sw2at-tw 0.0.4 ruby lib

Gem::Specification.new do |s|
  s.name = "sw2at-tw"
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Vitaly Tarasenko"]
  s.date = "2015-06-24"
  s.description = " You can define your own strategies for test data generation. And simply create them in RSpec tests. "
  s.email = "vetal.tarasenko@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/sw2at-tw.rb",
    "lib/swat/test_world/base.rb",
    "lib/swat/test_world/config.rb",
    "lib/swat/test_world/generators/install_generator.rb",
    "lib/swat/test_world/rspec_setup.rb",
    "lib/swat/test_world/templates/helpers.rb",
    "lib/swat/test_world/templates/methods.rb",
    "lib/swat/test_world/templates/test_world_subclass.rb",
    "sw2at-tw.gemspec"
  ]
  s.homepage = "http://github.com/tw4qa/sw2at-tw"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Swat Test World - Helper for test data generation."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<timecop>, ["~> 0.7.1"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<timecop>, ["~> 0.7.1"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<timecop>, ["~> 0.7.1"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

